### PR TITLE
Remove completion hashbang

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Comment by tavianator** [comment]
Why?  The `#!/hint/bash` shebang serves as a hint to text editors about what flavour of shell it is.

**Comment by a1346054** [comment]
Not a single completion file in /usr/share/bash-completion/completions/ does that, and various tools even throw warnings such as https://lintian.debian.org/tags/bash-completion-with-hashbang

Additionally, #!/hint/bash is not used anywhere else as far as I can tell.

There are a few typical ways of indicating filetype if necessary, such as including `# shellcheck shell=bash` for shellcheck, or the various ways of informing vim like `vim:ft=sh` if that is desired.

**Comment by tavianator** [comment]
True but `#!/hint/bash` should work pretty much universally without needing a separate modeline for every editor/tool in use.  (Then again, the `.bash` extension is probably enough.)  I guess I picked it up from Arch Linux, which uses it for things like `/etc/makepkg.conf`.

**Comment by tavianator** [comment]
Anyway, both consistency with other completion scripts and that Debian lint seem like good reasons to take this change.  Do you mind adding that reasoning to the commit message?

Also a couple more words in the second commit would be good, even just "whitespace fix" or something.

**Comment by a1346054** [comment]
I'm happy to reword it even more if you have any other suggestions.

One issue I previously spotted was that files sporadically gain/lose executable bits when cloned/copied onto windows machines, where cygwin/WSL might try to execute /hint/bash . I don't know how to reliably replicate that behavior though, and don't know how much of a problem it would cause anyway on windows if a non-existent file were to be attempted to be executed.

**Pull request merged**
