### PR TITLE
Macos fixes

### PR DESCRIPTION
**Pull request by tavianator**
Addresses #12, hopefully!  @aktau if this works for you, I'll merge.

### CODE REVIEW

**Comment by aktau** [comment]
Nope:

```
cc -D_DEFAULT_SOURCE -D_GNU_SOURCE -DBFS_VERSION=\"0.82-12-g28ee324\"  -std=c99 -g -Wall -MD -MP -MF eval.d -c eval.c -o eval.o
eval.c:791:12: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        int ret = clock_gettime(BFS_CLOCK, ts);
                  ^
eval.c:791:26: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        int ret = clock_gettime(BFS_CLOCK, ts);
                                ^
eval.c:781:20: note: expanded from macro 'BFS_CLOCK'
#       define BFS_CLOCK CLOCK_MONOTONIC
                         ^
1 warning and 1 error generated.
make: *** [eval.o] Error 1
```

**Comment by aktau** [comment]
Note that it complains about `clock_gettime` not even being defined.

**Comment by aktau** [comment]
This SO answer provides some alternatives: http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x. I haven't looked at how you actually use the clock (does it need to be seconds from epoch)? If it's just for timing, the `mach_` functions would be best. Even if it isn't, a `mach_` offset from `gettimeofday` would be a good choice I think.

**Comment by tavianator** [comment]
Fixed the test, try again?

**Comment by aktau** [comment]
It appears that in `eval.c` you're using it for profiling, for which `mach_absolute_time` is ideal. I've implemented this for neovim once. Here's an attempt that tries to be as uninvasive as possible. It applies to commit 28ee324f5f49c637f669b1e3ba8c5b98755efaf6.

I changed `struct parser_stat`'s `now` field into a `timeval` from a `timespec` because then I wouldn't need to use `clock_gettime` (I can use `gettimeofday`). I didn't think it was very important since generally people don't specify times in nanoseconds when they're typing find/bfs on the command line. The time it takes for the shell to evaluate the arguments is already more than a microsecond, for sure.

There's likely other solutions, as detailed in that SO answer.

```diff
From 02f53c5815fdb44764fef6b47aed5dfdd9c6f32f Mon Sep 17 00:00:00 2001
From: Nicolas Hillegeer <nicolas@hillegeer.com>
Date: Sun, 23 Oct 2016 21:38:52 +0200
Subject: [PATCH] macos: fix time incompatibilities

Fixes #12.
---
 eval.c  | 67 +++++++++++++++++++++++++++++++++++++++--------------------------
 parse.c | 21 +++++++++++++++------
 2 files changed, 55 insertions(+), 33 deletions(-)

diff --git a/eval.c b/eval.c
index d43a8c7..7fd2e55 100644
--- a/eval.c
+++ b/eval.c
@@ -777,27 +777,6 @@ bool eval_xtype(const struct expr *expr, struct eval_state *state) {
 	return false;
 }
 
-#if _POSIX_MONOTONIC_CLOCK
-#	define BFS_CLOCK CLOCK_MONOTONIC
-#elif _POSIX_TIMERS
-#	define BFS_CLOCK CLOCK_REALTIME
-#endif
-
-/**
- * Call clock_gettime(), if available.
- */
-static int eval_gettime(struct timespec *ts) {
-#ifdef BFS_CLOCK
-	int ret = clock_gettime(BFS_CLOCK, ts);
-	if (ret != 0) {
-		perror("clock_gettime()");
-	}
-	return ret;
-#else
-	return -1;
-#endif
-}
-
 /**
  * Record the time that elapsed evaluating an expression.
  */
@@ -813,6 +792,43 @@ static void add_elapsed(struct expr *expr, const struct timespec *start, const s
 	}
 }
 
+#ifdef __MACH__
+#include <mach/mach_time.h>
+#endif
+
+/* Get high resolution time in nanoseconds since a fixed time. */
+static struct timespec hrtime() {
+#ifdef __MACH__
+	/* Initialize the mach timebase struct, otherwise mach_absolute_time is
+	 * in meaningless units and we can't convert to timespec. If we ever
+	 * want to multithread, we need atomic load/stores here. */
+	static mach_timebase_info_data_t timebase = {0};
+	if (timebase.denom == 0) {
+		mach_timebase_info(&timebase);
+	}
+
+	/* Get the time in CPU dependent mach time units. */
+	uint64_t t = mach_absolute_time();
+
+	/* Technically, we could overflow, which is why, but substracting two
+	 * unsigned integers is well-defined (which we'll do later to get the
+	 * nanoseconds passed). It's tricky to do this with struct timespec's
+	 * though. It'd be better to just pass nanoseconds around and convert to
+	 * timespec only when needed. */
+	uint64_t nsec = (t * timebase.numer) / timebase.denom;
+	return (struct timespec){
+		.tv_sec = nsec / NSEC_PER_SEC,
+		.tv_nsec = nsec % NSEC_PER_SEC,
+	};
+#else
+	struct timespec ts;
+	if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
+		perror("clock_gettime()");
+	}
+	return ts;
+#endif
+}
+
 /**
  * Evaluate an expression.
  */
@@ -820,17 +836,14 @@ static bool eval_expr(struct expr *expr, struct eval_state *state) {
 	struct timespec start, end;
 	bool time = state->cmdline->debug & DEBUG_RATES;
 	if (time) {
-		if (eval_gettime(&start) != 0) {
-			time = false;
-		}
+		start = hrtime();
 	}
 
 	bool ret = expr->eval(expr, state);
 
 	if (time) {
-		if (eval_gettime(&end) == 0) {
-			add_elapsed(expr, &start, &end);
-		}
+		end = hrtime();
+		add_elapsed(expr, &start, &end);
 	}
 
 	++expr->evaluations;
diff --git a/parse.c b/parse.c
index 5761dc3..5905757 100644
--- a/parse.c
+++ b/parse.c
@@ -24,6 +24,7 @@
 #include <string.h>
 #include <sys/types.h>
 #include <sys/stat.h>
+#include <sys/time.h>
 #include <time.h>
 #include <unistd.h>
 
@@ -209,7 +210,7 @@ struct parser_state {
 	bool just_info;
 
 	/** The current time. */
-	struct timespec now;
+	struct timeval now;
 };
 
 /**
@@ -694,13 +695,21 @@ static struct expr *parse_access(struct parser_state *state, int flag, int arg2)
 	return expr;
 }
 
+/* Upsample a timespec to a timeval. */
+static struct timespec timeval_to_timespec(const struct timeval tv) {
+	return (struct timespec){
+		.tv_sec = tv.tv_sec,
+		.tv_nsec = tv.tv_usec * 1000ULL,
+	};
+}
+
 /**
  * Parse -[acm]{min,time}.
  */
 static struct expr *parse_acmtime(struct parser_state *state, int field, int unit) {
 	struct expr *expr = parse_test_icmp(state, eval_acmtime);
 	if (expr) {
-		expr->reftime = state->now;
+		expr->reftime = timeval_to_timespec(state->now);
 		expr->time_field = field;
 		expr->time_unit = unit;
 	}
@@ -763,7 +772,7 @@ static struct expr *parse_daystart(struct parser_state *state, int arg1, int arg
 		return NULL;
 	}
 
-	if (tm.tm_hour || tm.tm_min || tm.tm_sec || state->now.tv_nsec) {
+	if (tm.tm_hour || tm.tm_min || tm.tm_sec || state->now.tv_usec) {
 		++tm.tm_mday;
 	}
 	tm.tm_hour = 0;
@@ -777,7 +786,7 @@ static struct expr *parse_daystart(struct parser_state *state, int arg1, int arg
 	}
 
 	state->now.tv_sec = time;
-	state->now.tv_nsec = 0;
+	state->now.tv_usec = 0;
 
 	return parse_nullary_positional_option(state);
 }
@@ -1987,8 +1996,8 @@ struct cmdline *parse_cmdline(int argc, char *argv[]) {
 		.just_info = false,
 	};
 
-	if (clock_gettime(CLOCK_REALTIME, &state.now) != 0) {
-		perror("clock_gettime()");
+	if (gettimeofday(&state.now, NULL) != 0) {
+		perror("gettimeofday()");
 		goto fail;
 	}
 
-- 
2.7.4 (Apple Git-66)
```

**Comment by tavianator** [comment]
Thanks!  Totally missed the `parse.c` call to `clock_gettime()`.  I added a fallback for that one too.

I don't think I'm going to take the `mach_absolute_time()` stuff, as it's untestable for me, and `-D rates` isn't important enough to justify it IMO.

**Comment by aktau** [comment]
Thanks! It compiles and runs (and prints a file tree). I didn't try any options, but then again I don't really care about those :).

**Pull request merged**
