### PR TITLE
Documentation Refactoring

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the **[Preview]**.

*I haven't touched the individual topics for now.*

*I moved 'Features' into Usage to later separate*
*them from the usage instructions.*

<br>

### Changes

- Moved install / usage into dedicated files
- Moved changelog / contribute into docs folder
- Converted raw links into link references
- General formatting / spacing

[Preview]: https://github.com/ElectronicsArchiver/bfs

### CODE REVIEW

**Comment by tavianator** [comment]
I have to say, this looks pretty good!  I'm impressed.

**Comment by ElectronicsArchiver** [comment]
Oh thank goodness you like it,
was worried that you'd also be
of the old C way and want near
0 formatting.

*Guess I'll work on the rest~*

**Comment by data-man** [comment]
The existing README is compact and user-friendly.

**Comment by data-man** [comment]
Counter proposals:
- enable wiki (an user can clone `tavianator/bfs.wiki.git` if he want)
- add the Repology's badge to `Packaging status` wiki-page

[Packaging status](https://repology.org/project/bfs/versions)

**Comment by ElectronicsArchiver** [comment]
If you had ever worked as **a contributor** to someones wiki, you'd know the displeasure it is~

There aren't really any pros for it either, but there sure are cons.

Also, doesn't this counter your point you just made?

You don't want the documentation to be properly split up but in one 'compact' README, but then propose using GitHubs tragedy, sorry I mean wiki, which works on the principle of pages, ergo **splitting content up**.

**Comment by ElectronicsArchiver** [comment]
@tavianator 

<br>

Here are the links to all the files btw:
- **[README]**
- **[Install]**
- **[Build]**
- **[Usage]**
- **[Contribute]**
- **[Design]**
- **[Testing]**
- **[Hacking]**
- **[Makefile]**

<br>

*I was thinking on working on the changelog*
*on a followup PR, considering it''s length~*

<br>

[Makefile]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Makefile.md
[Hacking]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Hacking.md
[Testing]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Testing.md
[Design]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Design.md
[Contribute]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Contribute.md
[Usage]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Usage.md
[Build]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Build.md
[Install]: https://github.com/ElectronicsArchiver/bfs/blob/Build/docs/Install.md
[README]: https://github.com/ElectronicsArchiver/bfs

**Comment by tavianator** [comment]
I'm closing this since it's out of date with #91 being merged.  You're welcome to suggest further changes on top of it.  Thanks for the work you put into this!

**Pull request closed without merging**
